spring:
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: DASHSCOPE_API_KEY
      chat:
        options:
          model: qwen-plus-2025-07-28
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB